### ISSUE TITLE
Learn about Git

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#10]
There are three resources in the wiki to learn more about Git. I'm adding the same links here for reference:

- [Git For Ages 4 And Up] (https://www.youtube.com/watch?v=1ffBJ4sVUb4)
- [Learn Git Branching] (https://learngitbranching.js.org/)
- [The Git Book] (https://git-scm.com/book/en/v2)

These people mentioned in the first meeting that they would watch the Git For Ages 4 And Up video:

- [x] #41
- [x] #42
- [x] #43
- [x] #44
- [x] #45
- [x] #46

Other people who feel they should spend some time learning more about Git, please edit this comment and add a new task under your name. Also, add yourself as an assignee to this issue.

**Comment by ArdaYalcindag** [comment]
I have finished watching Git For Ages 4 And Up.

**Comment by ounuvar** [comment]
I'm splitting this up into multiple issues. Everyone will have their own "Learn about Git" issue. This will make tracking and closing issues easier.

**Comment by ounuvar** [comment]
I'm leaving myself as the only assignee to keep track of everyone left who hasn't watched  "Git For Ages 4 And Up".

**Comment by ounuvar** [comment]
Everyone who needed to watch "Git For Ages 4 And Up" has watched it. Closing issue.
