### ISSUE TITLE
Divide into Backend, Web, and Mobile Subteams

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#101]
## Description

Divide the team into backend, web, and mobile subteams.

***

## Acceptance Criteria
- [x] Create a Google Form for the team members to fill in.
- [x] Collect the response of each team member.
- [x] Divide into subteams according to the results of the Google Form.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by ahmetfirat23** [comment]
Teams were split as follows
-Mobile : Orhan-Ahmet-Taha
-Web: Su-Soner-Fırat-Yusuf
-Backend: Işıl-Arda-Batuhan

Members may change according to iccuring implementation problems.
