### ISSUE TITLE
Create Use-Case Diagram

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#104]
## Description

This task includes creating an use-case diagram following the points that were mentioned in the lectures. It must have its own page on the wiki.

***

### Reviewer:
This issue will be reviewed by: _@ounuvar_

**Comment by ahmetfirat23** [comment]
Here is our use case diagram: https://lucid.app/documents/view/cea13d55-e07c-4406-8b9f-6c25fe06d278. I will open the page in a minute.

**Comment by ahmetfirat23** [comment]
added it to the pages, please review @ounuvar

**Comment by ounuvar** [comment]
I reviewed the use-case diagram, it looks good 👍
