### ISSUE TITLE
Redo Scenario 5

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#105]
## Description

Sceneerio 5 had incorrect aspects due to timeline problems. The scenario itself needs to be redone and following mockups must be created. This scenario must focus on semantic browsing aspects of the app.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by sonerkuyar** [comment]
@ahmetfirat23 I couldn't remember if we delve into capabilities and scope of the semantic search in the meetings.
Requirements say only "1.2.2.1 System shall provide semantic search for usernames, lists and games." about semantics search. These are more like lexical search things. Could we create an example  to use in scenario or discuss about it?

**Comment by ahmetfirat23** [comment]
We talked about this in last few meetings but maybe the terminology was a bit obscure. You can check 1.2.6. . It includes reaching a game from a different game navigating through different properties. If you have more questions feel free to ask or dm me.

**Comment by ahmetfirat23** [comment]
Since there was a confusion about this task I am extending its deadline by a half day, please complete before tomorrow 3pm so I can review it before milestone deadline.

**Comment by abayir41** [comment]
The mockups are ready, I am waiting for Scenario 5 to be changed

**Comment by sonerkuyar** [comment]
@abayir41 @ahmetfirat23 I reorganized the [Scenario 5](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-5). Let me know if anything less or more.

**Comment by abayir41** [comment]
I have uploaded and match mockups with scenario items

**Comment by ahmetfirat23** [comment]
I have reviewed the page, I have two small objections. First one is that, at sixth scenario item, requirement specifies that anything other than usernames, lists and games must be one to one matched when searching. So it would be better if she couldn't remember one of these. Second is that other scenarios follow a structure that this scenario diverts from. Can you check the format of previous ones and change accordingly? It shouldn't be much trouble you just need to copy paste some lines. After doing these changes there is no need of reviewing again, feel free to close the issue.
@sonerkuyar

**Comment by ahmetfirat23** [comment]
Since the critical part of this issue was completed I am deprioritizing it.
