### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#106]
## Description

This task includes creation of sequence diagrams. There should be many diagrams following different cases. Also all diagrams should be in one page.

***

### Reviewer:
This issue will be reviewed by: _@ArdaYalcindag_

**Comment by ahmetfirat23** [comment]
@e-taha @isilsukarakuzuu @yusufaygun @ArdaYalcindag  This issue has been quite so far, is everything okey?

**Comment by isilsukarakuzuu** [comment]
Sorry for the delay, we are working through it with @yusufaygun

**Comment by yusufaygun** [comment]
we had a meeting with @isilsukarakuzuu and @e-taha and shared the diagrams among us as follows:
yusuf: view profile, logged in user interactions and guest user interactions diagrams
ışıl: view main page, search, notification and admin diagrams
taha: review, game and list diagrams
we will finish the diagrams until our weekly meeting on wednseday at latest.

**Comment by ahmetfirat23** [comment]
> we had a meeting with @isilsukarakuzuu and @e-taha and shared the diagrams among us as follows: yusuf: view profile, logged in user interactions and guest user interactions diagrams ışıl: view main page, search, notification and admin diagrams taha: review, game and list diagrams we will finish the diagrams until our weekly meeting on wednesday at latest.

Still no progress? Folks this is a critical milestone 2 task which is past due by 4 days. Please complete very very urgently. @yusufaygun @isilsukarakuzuu @e-taha

**Comment by isilsukarakuzuu** [comment]
I initialized the page, now adding my part. You can check here:
[Sequence Diagram](https://github.com/bounswe/bounswe2024group12/wiki/Sequence-Diagram)

**Comment by e-taha** [comment]
The page is already initialized by @yusufaygun . [Sequence Diagrams](https://github.com/bounswe/bounswe2024group12/wiki/Sequence-Diagrams)

**Comment by e-taha** [comment]
I will be adding there, 4 remaining.

**Comment by isilsukarakuzuu** [comment]
Wish you would have informed me, the link was neither on the sidebar nor on the homepage. I added the link I opened to both of them, now I will have to change it. Please include the link where it should be when initializing a page.

**Comment by isilsukarakuzuu** [comment]
I deleted the page that I opened, and moved sequence diagrams for admin and search to the original page. I am waiting @ounuvar to add notifications to class diagram so I can complete notifications seq. diagram. Also I have a few questions regarding main page seq. diagram. When I resolve them I will add it also.

**Comment by isilsukarakuzuu** [comment]
Also do you think I need to detail admin sequence diagrams, such as explaining how validation and deletions work etc. @e-taha @yusufaygun ?

**Comment by yusufaygun** [comment]
> Wish you would have informed me, the link was neither on the sidebar nor on the homepage. I added the link I opened to both of them, now I will have to change it. Please include the link where it should be when initializing a page.

Sorry for that, I opened the page to work on my diagrams but I did not finalized my diagrams yet and I forgot to add them to the sidebar or homepage. I will now finish the diagrams but I have some questions: 
- Which commands do we need to use when retrieving data from database, is it okay to leave that part as a sentence or should we use commands?
- Will the actions follow, unfollow etc. be done from the other user's userpage? if so, is it like this: `user -> viewProfile(user) -> followUser(user)`, or is it directly like this: `user -> followUser(user`) ?
- I noticed that some functions like friend requests or unfollow are not mentioned in use-case diagram, should we also add these features to sequence diagram?
@ahmetfirat23, @ounuvar (I thought you could help me about these questions since you created requirements and other diagrams , thanks in advance)

**Comment by ounuvar** [comment]
> I deleted the page that I opened, and moved sequence diagrams for admin and search to the original page. I am waiting @ounuvar to add notifications to class diagram so I can complete notifications seq. diagram. Also I have a few questions regarding main page seq. diagram. When I resolve them I will add it also.

I will add notifications to the class diagram tomorrow.

**Comment by ahmetfirat23** [comment]
> * I noticed that some functions like friend requests or unfollow are not mentioned in use-case diagram, should we also add these features to sequence diagram?
>   @ahmetfirat23, @ounuvar (I thought you could help me about these questions since you created requirements and other diagrams , thanks in advance)

I strongly believe we won't be doing friend requests which was a good to have (should) in the requirements so I don't want to overcomplicate the use-case diagram. I added other ones. If you find anything else missing please open a new issue, it is a bit difficult to keep track of what to update from issue comments.

**Comment by isilsukarakuzuu** [comment]
@ahmetfirat23 last changes are made in this issue, can you check it again?

**Comment by ahmetfirat23** [comment]
lgtm
