### ISSUE TITLE
Update the About section of the wiki home page

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#110]
## Description

Update the About section on the wiki home page to describe the application "Playlog" we are building. Mention what Playlog is and what users can do in Playlog. It can be brief, 5-10 sentences max.

***
## Acceptance Criteria
- [x] Update the About section on the wiki home page.

**Comment by ahmetfirat23** [comment]
I have done this to add the deployment link though later we can write a long and better text
