### ISSUE TITLE
Fix Scenarios

### ISSUE THREAD

**Issue by ArdaYalcindag** [bounswe/bounswe2024group12#111]
## Description

Scenarios need some small corrections.

***

## Acceptance Criteria
- [x] The second sentence in [Scenario 1](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-1) does not conform to requirements since you need to login after sign up. Fix it.
- [x] Convert **Games to Play** to **Playlist** so that scenarios and requirements are compatible.
- [x] Remove the **commenting on a user's list** and **liking a user's list** features from [Scenario 3](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-3).
- [x] Revise [Scenario 4](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-4) so that it follows the requirements
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ArdaYalcindag** [comment]
@ahmetfirat23 Can you check whether there are more errors need to be fixed about scenarios?

**Comment by ounuvar** [comment]
For the second acceptance criteria, could you change the wording in the scenarios so that it is clear that instead of a new custom list called "Games to Play" is created, the user uses the default list called "Playlist" which essentially serves that exact purpose. Think of this like the "Watch Later" list in YouTube (that is default, and you cannot remove it afaik) @ArdaYalcindag

**Comment by ounuvar** [comment]
Also in scenario 3 there is "commenting on a user's list" and "liking a user's list". We didn't plan these features, they are neither in the requirements nor in the design. I suggest removing the mention of these from Scenario 3 @ArdaYalcindag

**Comment by ounuvar** [comment]
> > For the second acceptance criteria, could you change the wording in the scenarios so that it is clear that instead of a new custom list called "Games to Play" is created, the user uses the default list called "Playlist" which essentially serves that exact purpose. Think of this like the "Watch Later" list in YouTube (that is default, and you cannot remove it afaik) @ArdaYalcindag
> 
> I think this is the same problem with the second acceptance criteria of this issue, isn’t it? I will fix it.

Yes, I wanted to clarify the fix for that acceptance criteria.

**Comment by ounuvar** [comment]
Could you fix the second sentence in Scenario 1? There is no automatic redirection to the website/app after email confirmation, user needs to manually log in.

**Comment by ounuvar** [comment]
@ahmetfirat23 You mentioned at some point that there was some wrong mention of adding description to a profile in one of the scenarios? I couldn't find where it is.

**Comment by ahmetfirat23** [comment]
> @ahmetfirat23 You mentioned at some point that there was some wrong mention of adding description to a profile in one of the scenarios? I couldn't find where it is.

I believe it was fifth scenario but Soner already fixed that with a complete rewrite.

**Comment by ounuvar** [comment]
In Scenario 4 it says:  "Sara goes to her user page. Here, she can view her gaming activity and preferences. On her user page, Sara navigates to the section that displays her favorite games. She sees a list of games she has previously liked, but it's not organized in any specific order."

What does the "section that displays her favorite games" mean? There is no such section in a user's profile page, please correct me if I'm wrong @ahmetfirat23.

The rest of the scenario continues as: "Sara wants to identify her top-rated games, so she looks for a filter option. She clicks the button named sort by and selects the top rated option."

We already discussed with @ahmetfirat23 in #112 that we don't have a filtering feature inside lists. I think the confusion arose because the Figma design itself is misleading and shows a filtering button on a list page. We should probably fix that as well.

**Comment by ArdaYalcindag** [comment]
> In Scenario 4 it says: "Sara goes to her user page. Here, she can view her gaming activity and preferences. On her user page, Sara navigates to the section that displays her favorite games. She sees a list of games she has previously liked, but it's not organized in any specific order."
> 
> What does the "section that displays her favorite games" mean? There is no such section in a user's profile page, please correct me if I'm wrong @ahmetfirat23.
> 
> The rest of the scenario continues as: "Sara wants to identify her top-rated games, so she looks for a filter option. She clicks the button named sort by and selects the top rated option."
> 
> We already discussed with @ahmetfirat23 in #112 that we don't have a filtering feature inside lists. I think the confusion arose because the Figma design itself is misleading and shows a filtering button on a list page. We should probably fix that as well.

Looks like scenario 4 needs some major changes. I'm adding @yusufaygun as assignee too to revise scenario 4.

**Comment by ahmetfirat23** [comment]
> In Scenario 4 it says: "Sara goes to her user page. Here, she can view her gaming activity and preferences. On her user page, Sara navigates to the section that displays her favorite games. She sees a list of games she has previously liked, but it's not organized in any specific order."
> 
> What does the "section that displays her favorite games" mean? There is no such section in a user's profile page, please correct me if I'm wrong @ahmetfirat23.

I think this one exists. Check requirement 1.1.3.5.2.

**Comment by ounuvar** [comment]
> > In Scenario 4 it says: "Sara goes to her user page. Here, she can view her gaming activity and preferences. On her user page, Sara navigates to the section that displays her favorite games. She sees a list of games she has previously liked, but it's not organized in any specific order."
> > What does the "section that displays her favorite games" mean? There is no such section in a user's profile page, please correct me if I'm wrong @ahmetfirat23.
> 
> I think this one exists. Check requirement 1.1.3.5.2.

The description of it in the scenario is wrong, though. There are 2 separate features:

1. Liking a game from the game page: This is just like a simple upvote, you can't see it on any user's profile page. It is just an attribute of each game (number of people who liked the game) that could potentially be useful while doing search (e.g., search for highly liked games). A user can like as many games as they want. (see requirements 1.1.3.2.1. and 1.1.3.2.2.)

2. Setting a game as favorite from the profile page: This is a more special interaction, a user can only set a fixed number of favorite games (decided to be 4 for now). And these ARE organized in a specific order, you can set your 1st favorite game, 2nd favorite game, etc. (see requirements 1.1.2.4.1. and 1.1.3.5.2.)

The description in the scenario is mixing up these two separate features. If it is trying to refer to the 1st feature, there is no such section on a profile page where we can see the games liked by a user. If it is trying to refer to the 2nd feature, then the description in the scenario should fixed to specifically refer to the 2nd feature and not mix it up with the 1st feature.

**Comment by ounuvar** [comment]
I think the design in Figma is missing the UI for the 1st feature. Should we open an issue to add that to the design?

**Comment by yusufaygun** [comment]
I updated [Scenario 4](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-4) according to your feedbacks and now it is consistent with the requirements I guess. Sorry for the delay, I didn't have a chance to handle it sooner.

**Comment by ahmetfirat23** [comment]
lgtm
