### ISSUE TITLE
Add the review filtering use case to the use case diagram

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#112]
## Description

The use case diagram is missing the filtering reviews under a game by rating use case. Add this to the use case diagram.

***

### Reviewer:
This issue will be reviewed by: _@ounuvar_

**Comment by ounuvar** [comment]
Our Figma design also includes filtering for the games in a list. But we didn't put this in the requirements. Should we remove it from the design or instead add it to the requirements? @ahmetfirat23

**Comment by ahmetfirat23** [comment]
> Our Figma design also includes filtering for the games in a list. But we didn't put this in the requirements. Should we remove it from the design or instead add it to the requirements? @ahmetfirat23

Though this is not use case related, I don't think this was something discussed. We don't filter games. Please further discuss this under #111 after refering this comment.

**Comment by ahmetfirat23** [comment]
I added filter by review case. I don't think this issue needs to be reviewed so I am closing it myself. Please feel free to open another issue if you find something missing.
