### ISSUE TITLE
Create Review Mockup

### ISSUE THREAD

**Issue by asyasusen** [bounswe/bounswe2024group12#116]
## Description

Kutay talked about making reviews more clear and detailed. I think it is a good idea to add a review mockup to the mockup page. You can check out [class diagrams](https://lucid.app/lucidchart/7a24db6e-4759-44b3-867b-413777a66639/edit?beaconFlowId=C5F14817DBA56053&invitationId=inv_78882e5b-6f04-4c0b-bf27-9857ee31487a&page=0_0#) to get an idea.

### Reviewer:
This issue will be reviewed by: @asyasusen

**Comment by isilsukarakuzuu** [comment]
I can do this after Wednesday, since I have 2 issues that has higher priority due to Wednesday. (#126 and #106)
@e-taha, @abayir41 do you have availability for this task?

**Comment by asyasusen** [comment]
@isilsukarakuzuu so should I close this issue since review is already implemented?

**Comment by isilsukarakuzuu** [comment]
Yes, I'm closing now.
