### ISSUE TITLE
Update Requirements Security Part

### ISSUE THREAD

**Issue by asyasusen** [bounswe/bounswe2024group12#117]
## Description

Update the security section of requirements according to feedback From Kutay. KCVV doesn't count as a security. Instead we should specify stuff like password encryption

**Comment by asyasusen** [comment]
Done

**Comment by asyasusen** [comment]
> I think TA was expecting more details on this section. Also KVCC should still be included somewhere in the requirements. Can you inspect some old repos for ideas?

Didn't the TA say that KVCC might be a too big for our scope? Other than that I'll fix it accordingly. We haven't decided on how we'll encrypt so I'm waiting on that to update

**Comment by ahmetfirat23** [comment]
I can't confidently remember what he said but I believe KVKK automatically applies to everything so I think we should be considering it. We may ask to TA again too.

**Comment by ahmetfirat23** [comment]
@asyasusen Is there any update you are planning to on this?

**Comment by asyasusen** [comment]
> @asyasusen Is there any update you are planning to on this?

Can you review my changes, I've added encryption and KVCC

**Comment by ahmetfirat23** [comment]
> > @asyasusen Is there any update you are planning to on this?
> 
> Can you review my changes, I've added encryption and KVCC

I still believe this section lacks depth. Can you please check other groups security sections?
