### ISSUE TITLE
Create issue template temporarily in wiki

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#12]
Come up with an issue categorization scheme and create a template for each issue category.

**Comment by isilsukarakuzuu** [comment]
@ahmetfirat23, I'm assigning you and unassigning others as we've decided you'll be responsible for creating the issue templates in the wiki. Additionally, I'm updating the issue for clarity. @abayir41 @ounuvar fyi.

**Comment by isilsukarakuzuu** [comment]
The task to be explained: Temporarily create issue template in wiki; plan to move it to the codebase with .yml files later.

**Comment by ahmetfirat23** [comment]
I wrote the issue template and added it to the sidebar. Can you please check and feedback @ounuvar ?

**Comment by ounuvar** [comment]
Looks great. Simple and useful. I think we can directly add this to the repo. Closing the issue.
