### ISSUE TITLE
Organize Project Plan

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#120]
## Description

Our project plan needs further refinement. This tasks includes opening up the main project components. Also all sub-teams should include their plan in the #96 and include start and end dates so the tasks are displayed in timeline. Please assign yourselves to this issue for your subteam's plan.

***

## Acceptance Criteria
- [x] Front-end plan
- [x] Back-end plan
- [x] Mobile plan
- [x] Testing plan
- [x] Deployment plan
<br>

***

### Reviewer:
This issue will be reviewed by all subteams

**Comment by ahmetfirat23** [comment]
I included our plan for frontend. I refined a bit the testing and deployment part however I don't have too much idea about those activities now so they definitely need reviewing. Also please create a roadmap of your subteam and include it in the project roadmap in a similar format to ours.

**Comment by isilsukarakuzuu** [comment]
Let's talk about this in our second meeting, Wednesday. @mbatuhancok @ArdaYalcindag

**Comment by ahmetfirat23** [comment]
@isilsukarakuzuu have you decided anyone on the plan to add your plan?

**Comment by ahmetfirat23** [comment]
@e-taha @ounuvar @abayir41 also can you please include your mobile plan and create a plan for testing and development after the milestone?

**Comment by ounuvar** [comment]
> @e-taha @ounuvar @abayir41 also can you please include your mobile plan and create a plan for testing and development after the milestone?

Noted.

**Comment by ahmetfirat23** [comment]
Orhan added mobile plan I added other plans due to unresponsiveness.
