### ISSUE TITLE
Implement Login and Signup Page Design

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#121]
## Description

Implement the main layout for login and signup pages. Pages must have input fields that were specified in the requirements. Visual aspects must be completed for this task and no functionality required.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by sonerkuyar** [comment]
I ended up the Signup and Login page design. Please check the related commit.

**Comment by ahmetfirat23** [comment]
LGTM however should we add a section "Already registered? Login" in signup page that directs to login page?

**Comment by sonerkuyar** [comment]
> LGTM however should we add a section "Already registered? Login" in signup page that directs to login page?

I think also it might be useful but I can't see this feature in neither requirements nor mock-ups.

**Comment by ahmetfirat23** [comment]
That's a fair point. Maybe we can reiterate on this later. Fn I took this as a successful completion.
