### ISSUE TITLE
Revise Requirements acc to feedback

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#123]
## Description

In our last meeting with TA, he gave us some feedbacks about requirements. We need to revise our requirements according to his feedback which are documented in the meeting notes.

***

### Reviewer:
This issue will be reviewed by: _@asyasusen_

**Comment by ahmetfirat23** [comment]
@ounuvar Can you take care of the feedback about reviews?

**Comment by ounuvar** [comment]
> @ounuvar Can you take care of the feedback about reviews?

I will do it as soon as I have time.

**Comment by ahmetfirat23** [comment]
@ounuvar please don't forget this before deadline. however don't change the numbering of requirements since we cant update scenarios.

**Comment by ounuvar** [comment]
The requirements are updated according to the feedback from the TA without changing their numbering. The latest version of the requirements can be found [here](https://github.com/bounswe/bounswe2024group12/wiki/Requirements).
