### ISSUE TITLE
Add Meeting Notes 6-7-8 and Backend Meeting 1

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#124]
## Description

Add Meeting Notes 6-7-8 and Backend Meeting 1. Add links to wiki sidebar and wiki homepage.

***

## Acceptance Criteria
- [x] Meeting Note 6 added.
- [x] Meeting Note 7 added.
- [x] Meeting Note 8 added.
- [x] Backend - Meeting Note 1 added.
- [x] Meeting Note 6 link added to wiki sidebar and wiki homepage. 
- [x] Meeting Note 7 link added to wiki sidebar and wiki homepage. 
- [x] Meeting Note 8 link added to wiki sidebar and wiki homepage. 
- [x] Backend - Meeting Note 1 link added to wiki sidebar and wiki homepage. 
<br>...

@mbatuhancok can you add your notes you took after I left early to Meeting Notes 7?

***

### Reviewer:
This issue will be reviewed by: @ArdaYalcindag

**Comment by isilsukarakuzuu** [comment]
I apologize for the delay. I forgot to add the notes to the wiki when the Ramadan holiday intervened. I hope it wasn't too much of a problem since you can already access your notes from Drive :(

**Comment by isilsukarakuzuu** [comment]
I created different sub-titles for backend, frontend and mobile meeting notes. Don't forget to add yours for mobile and frontend @ahmetfirat23 @sonerkuyar @asyasusen @yusufaygun @e-taha @ounuvar @abayir41 (I don't know your note-takers so I tagged you all.)

**Comment by isilsukarakuzuu** [comment]
I finished my part, you can check here:
- [Meeting #8 ‐ 17.04.2024](https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%238-%E2%80%90-17.04.2024)
- [Meeting #7 ‐ 27.03.2024](https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%237-%E2%80%90-27.03.2024)
- [Meeting #6 ‐ 22.03.2024](https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%236-%E2%80%90-22.03.2024)
- [Backend ‐ Meeting #1 ‐ 21.04.2024](https://github.com/bounswe/bounswe2024group12/wiki/Backend-%E2%80%90-Meeting-%231-%E2%80%90-21.04.2024)

**Comment by isilsukarakuzuu** [comment]
@mbatuhancok can you take a look at this?

**Comment by yusufaygun** [comment]
I added frontend meeting note 1: [Frontend ‐ Meeting #1 ‐ 20.04.2024](https://github.com/bounswe/bounswe2024group12/wiki/Frontend-%E2%80%90-Meeting-%231-%E2%80%90-20.04.2024)

**Comment by ahmetfirat23** [comment]
@mbatuhancok Please complete this issue today

**Comment by mbatuhancok** [comment]
Done
