### ISSUE TITLE
Initialize the Backend side of the project

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#126]
## Description

Initialize the Django Project. Open a branch for backend-dev. Commit the initial project to backend branch. 

***

## Acceptance Criteria
- [x] Initialize the Django Project.
- [x] Open a branch for backend-dev.
- [x] Commit the initial project to backend branch. 
<br>...

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by isilsukarakuzuu** [comment]
Backend side of the project is initialized, I explained how to use it in [here](https://github.com/bounswe/bounswe2024group12/blob/backend-dev/backend/README.md). After reviewing, I think you can close this issue @ahmetfirat23

**Comment by ahmetfirat23** [comment]
I will test running it on my local later.

**Comment by ahmetfirat23** [comment]
I don't think I will be able to review this issue. Can you find someone else to review please? @isilsukarakuzuu
