### ISSUE TITLE
Implement fundamental components and text styles

### ISSUE THREAD

**Issue by e-taha** [bounswe/bounswe2024group12#129]
## Description

We need to implement some fundamental components and text styles that will be used in multiple screens/sections.

***

## Components
- [x] Button(Active-Disabled-TextActive-TextDisabled)
- [x] Game List Card
- [x] Review List Card
- [x] Game Card 
- [x] More Games Card(Grid) 
- [x] Main Page Review Card
- [x] Game Page Review Card(Editabe-nonEditable modes)
- [x] Favorite Game Properties List Card
- [x] Favorite Game Property Card
- [x] Game Page Banner
- [x] Main Page Banner
- [x] Small Ratings
- [x] Big Ratings
- [ ] Rating Histogram
- [x] Credits Card
- [x] Characters Card
- [ ] List Page List Card
- [ ] Sample List Mobile

## Text Styles
- [x] Default
- [x] Card Title
- [x] Title

***

### Reviewer:
This issue will be reviewed by: @e-taha

**Comment by ahmetfirat23** [comment]
This is a very huge task. Can you split this task into subtasks? Also can you put those tasks in a timeline and append it to the project plan? #120 we are supposed to complete this task urgently.

**Comment by e-taha** [comment]
Histogram and list properties were removed. Other than that, all of them were implemented. Closing issue
