### ISSUE TITLE
Personal page template

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#13]
Create a personal page template and place it as a separate page named "Personal Page Template" under the wiki.

**Comment by ArdaYalcindag** [comment]
Personal page template is created under home page. I created my own personal page and added link to home page. If you think something needs to be changed, let me know.

**Comment by ArdaYalcindag** [comment]
Personal page template is created under home page. I created my own personal page and added link to home page. If you think something needs to be changed, let me know.
