### ISSUE TITLE
API Integration for Login and Sign Up

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#131]
## Description

We need to integrate an assumed API for login and sign up pages. There might be small changes needed when backend completes their implementation. Currently on sign-up we should send username and hashed email and password to backend. We should determine the success of sign-up using the server response. On login we should send only hashed email and password. Also we should implement a page that user navigates after clicking the confirmation link that is sent to their mail after sign-up.

***

## Acceptance Criteria
- [x] Login API Integration
- [x] Sign-up API Integration
- [ ] Mail confirmation page

***

### Reviewer:
This issue will be reviewed by: _@sonerkuyar_

**Comment by ahmetfirat23** [comment]
Als what do you think about encryption: Should we use hashing or encrypting? I am currently coding for hashing and using SHA256 but do you think it is a proper use? Should we hash email address or just keep them as plain text? Also should we hash on frontend or backend? @asyasusen @sonerkuyar @isilsukarakuzuu @ArdaYalcindag @ounuvar @e-taha

**Comment by ahmetfirat23** [comment]
I pushed a simple request code to server-side for login and sign up functionalities. Also created a small server script for testing purposes you can check it from here: https://gist.github.com/ahmetfirat23/aa86f2cab2f8153705e19d05d19e390e

**Comment by asyasusen** [comment]
> Als what do you think about encryption: Should we use hashing or encrypting? I am currently coding for hashing and using SHA256 but do you think it is a proper use? Should we hash email address or just keep them as plain text? Also should we hash on frontend or backend? @asyasusen @sonerkuyar @isilsukarakuzuu @ArdaYalcindag @ounuvar @e-taha

From what I know encryption should be on the server/backend. As long as we are sending the plain text password over HTTPS, the password is safe. And I think SHA256 is more than enough for this phase

**Comment by e-taha** [comment]
> Als what do you think about encryption: Should we use hashing or encrypting? I am currently coding for hashing and using SHA256 but do you think it is a proper use? Should we hash email address or just keep them as plain text? Also should we hash on frontend or backend? @asyasusen @sonerkuyar @isilsukarakuzuu @ArdaYalcindag @ounuvar @e-taha



I think we shouldn't hash our e-mail. We can't revert the e-mail from the hash, but we may need the plain e-mail address across the app for a lot of places. Besides, it isn't sensitive data.

By the way, I think using bcrypt instead of SHA-256 would be a better choice for hashing passwords.

**Comment by sonerkuyar** [comment]
I edited @ahmetfirat23 server.js slightly [server.js].(https://gist.github.com/sonerkuyar/0e3ab3a2b6ef146d616df412dce618cel)

**Comment by ahmetfirat23** [comment]
We will do the main confirmation later, and it is more complicated then I though of. Other features were tested by the team.
