### ISSUE TITLE
Integrate a database to Django

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#134]
## Description

We should create a MYSQL database and integrate it to Django project. 

***

## Acceptance Criteria
- [x] MYSQL database is created and integrated to our project, backend-dev.
- [x] It is merged to dev.
- [x] It is merged to main.
<br>...

***

### Reviewer:
This issue will be reviewed by: @asyasusen

**Comment by isilsukarakuzuu** [comment]
MySQL database is set and integrated to our project, you can check [here](https://github.com/bounswe/bounswe2024group12/blob/backend-dev/backend/README.md) to see how to do it. Also I you can use 3rd party IDE's like TablePlus, MySQL IDE to see the database. I recommend [TablePlus](https://tableplus.com). @ArdaYalcindag @mbatuhancok @asyasusen @ahmetfirat23 @sonerkuyar

**Comment by ahmetfirat23** [comment]
This issue was done and merged to main.
