### ISSUE TITLE
Implement Game Page Frontend

### ISSUE THREAD

**Issue by asyasusen** [bounswe/bounswe2024group12#136]
## Description

We need to implemet game page frontend to showcase that the api is working.

***
## Acceptance Criteria
- [x] Game main info
- [x] Tab Structure
- [x] Game Tab
- [x] Characters Tab
- [x] Reviews Tab
- [x] Implement backend functions
<br>

### Reviewer:
This issue will be reviewed by: @ahmetfirat23 @sonerkuyar @yusufaygun

**Comment by asyasusen** [comment]
@ahmetfirat23 so there isn't a backend function yet for the tabs in the game page. And we don't have a mockup for the other tabs. For now I'll just put empty components that can be styled afterwards. Is that okay?

**Comment by ahmetfirat23** [comment]
Yes, please just include a sidebar at the right of the page. This wasn't in the mockup but we had it in initial plans. It includes the general properties of the game like publisher, developer, country of origin, fandom page wiki etc.

**Comment by ahmetfirat23** [comment]
For your reference
![20240426_190746](https://github.com/bounswe/bounswe2024group12/assets/69598652/d00e5017-3b07-418f-aaee-f84ed164f1c5)

**Comment by asyasusen** [comment]
I've got the main structure down. We'll continue when the api implementation is done

**Comment by sonerkuyar** [comment]
@asyasusen  LGTM thank you for your efforts and work, but there are things about UI. I wrote a card component under common directory you can use it. if you don't want to use it maybe you can make the cards more distinguishable from background.  Also your margins are suspicious. 
If you have time for design these got my attention.

**Comment by asyasusen** [comment]
> @asyasusen LGTM thank you for your efforts and work, but there are things about UI. I wrote a card component under common directory you can use it. if you don't want to use it maybe you can make the cards more distinguishable from background. Also your margins are suspicious. If you have time for design these got my attention.

Can you clarify what do you mean by margins are suspicious?

**Comment by isilsukarakuzuu** [comment]
> I've got the main structure down. We'll continue when the api implementation is done

I will be doing it, I opened an [issue](https://github.com/bounswe/bounswe2024group12/issues/191) for this endpoint

**Comment by asyasusen** [comment]
I've implemented the core-structure for the game-page I'll finish when you send me a response template

**Comment by asyasusen** [comment]
I've finished everything, credit tab was removed since we couldn't implement the backend function.

**Comment by ahmetfirat23** [comment]
We might have had fetch more information about games that we initially talked about. But I think this is issue is solved.
