### ISSUE TITLE
Implement Main screen design for mobile

### ISSUE THREAD

**Issue by e-taha** [bounswe/bounswe2024group12#138]
## Description

We need to implement the design of the Main screen. To do that, first, we need to implement the necessary components.

***

## Components that will be implemented
- [x] #145
- [x] Game Card
- [x] #148
- [x] #146
- [x] #147
- [x] #149

***

### Reviewer:
This issue will be reviewed by: @e-taha

**Comment by ounuvar** [comment]
All components in the main screen are implemented, reviewed by @e-taha, and merged into the main branch. I'm closing the issue.
