### ISSUE TITLE
Implement Game screen design for mobile

### ISSUE THREAD

**Issue by e-taha** [bounswe/bounswe2024group12#139]
## Description

We need to implement the design of the Game screen. To do that, first, we need to implement the necessary components.

***

## Components that will be implemented
- [x] #140
- [ ] Rating Histogram
- [x] #141
- [x] #142
- [x] #143
- [x] #144

***

### Reviewer:
This issue will be reviewed by: @e-taha

**Comment by ounuvar** [comment]
Rating histogram feature got scrapped. All the other listed features were implemented.
