### ISSUE TITLE
Add personal wiki page links to README.md

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#14]
Personal wiki page link of each team member should be added to README.md.

- [x] Ahmet Bayir
- [x] Ahmet Fırat Gamsız
- [x] Arda Yalcindag
- [x] Asya Su Sen
- [x] Mehmet Batuhan Cok
- [x] Isıl Su Karakuzu
- [x] Orhan Unuvar
- [x] Soner Kuyar
- [x] Taha Ensar Kukul
- [x] Yusuf Aygun

**Comment by isilsukarakuzuu** [comment]
Furthermore, they should be added to the wiki homepage and sidebar. All of these updates can be tracked through this issue as they are carried out concurrently.

**Comment by ahmetfirat23** [comment]
Sorry about the mention I mistyped.

**Comment by abayir41** [comment]
I added my page. As the last person doing this task, I am closing the issue
