### ISSUE TITLE
Game Page Review Card

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#140]
## Description

Design the component, the goal style of component can be seen below.

![Ekran Resmi 2024-04-27 18 57 04](https://github.com/bounswe/bounswe2024group12/assets/82515909/a5f8d7f8-1c56-4ec8-840e-248071609c46)

**Comment by ounuvar** [comment]
This component is implemented by @abayir41 and reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
