### ISSUE TITLE
Big Ratings

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#141]
## Description

Design the component, the goal style of component can be seen below.
![Ekran Resmi 2024-04-27 18 56 32](https://github.com/bounswe/bounswe2024group12/assets/82515909/9e12b735-fe0a-4711-a083-d526491a720f)

**Comment by ounuvar** [comment]
This component is implemented by @abayir41 and reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
