### ISSUE TITLE
Game Details Card

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#144]
## Description

Design the component, the goal style of component can be seen below.

![Ekran Resmi 2024-04-27 18 54 41](https://github.com/bounswe/bounswe2024group12/assets/82515909/3db3374a-bc53-4a50-ae80-75be255d257a)

**Comment by ounuvar** [comment]
This component is implemented by @abayir41 and reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
