### ISSUE TITLE
Review List Card

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#145]
## Description

Design the component, the goal style of component can be seen below.
![Ekran Resmi 2024-04-27 18 53 45](https://github.com/bounswe/bounswe2024group12/assets/82515909/9004b046-825b-4b6a-937a-f8d459ded01a)

**Comment by ounuvar** [comment]
I implemented the component and opened the following pull request #155 . Can you review it @e-taha ?

**Comment by ounuvar** [comment]
This component is reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
