### ISSUE TITLE
Main Page Review Card

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#146]
## Description

Design the component, the goal style of component can be seen below.
![Ekran Resmi 2024-04-27 18 52 56](https://github.com/bounswe/bounswe2024group12/assets/82515909/4dfe278c-dee9-4bcd-8dbc-7dfdb4adf964)

**Comment by ounuvar** [comment]
I implemented the MainPageReviewCard component and opened the following pull request https://github.com/bounswe/bounswe2024group12/pull/155 . Can you review it @e-taha ?

**Comment by ounuvar** [comment]
This component is reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
