### ISSUE TITLE
Main Page Banner

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#147]
## Description

Design the component, the goal style of component can be seen below.
![Ekran Resmi 2024-04-27 18 52 09](https://github.com/bounswe/bounswe2024group12/assets/82515909/6fb01116-2b20-4c93-9acd-05d20646294d)

**Comment by ounuvar** [comment]
I implemented the MainPageBanner component and opened the following pull request https://github.com/bounswe/bounswe2024group12/pull/155 . Can you review it @e-taha ?
