### ISSUE TITLE
More Games Card(Grid)

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#148]
## Description

Design the component, the goal style of component can be seen below.
![Ekran Resmi 2024-04-27 18 51 21](https://github.com/bounswe/bounswe2024group12/assets/82515909/c863d7e2-5de6-456d-84f0-050d29b5d809)

**Comment by e-taha** [comment]
It's done. But it can cause UI problems on small screens. We may look after the milestone
