### ISSUE TITLE
Small Ratings

### ISSUE THREAD

**Issue by abayir41** [bounswe/bounswe2024group12#149]
## Description

Design the component, the goal style of component can be seen below.

![Ekran Resmi 2024-04-27 18 49 25](https://github.com/bounswe/bounswe2024group12/assets/82515909/d94d5064-ace9-4520-bf56-4d1558410b0b)

**Comment by ounuvar** [comment]
This component is reviewed by @e-taha and then merged into the main branch. I'm closing the issue.
