### ISSUE TITLE
Create Dockerfile for Frontend

### ISSUE THREAD

**Issue by yusufaygun** [bounswe/bounswe2024group12#152]
## Description

Create Dockerfile for frontend and update the docker-compose file.

***

## Acceptance Criteria
- [x] Dockerfile is created in frontend-dev
- [x] Docker-compose file is updated
- [x] Docker files are merged to dev
- [x] Docker files are merged to main

***

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu and @sonerkuyar

**Comment by yusufaygun** [comment]
I created a Dockerfile and .dockerignore file and added it into frontend-dev, I will add the needed configurations to the docker-compose.yaml after we handle the structure properly.

**Comment by isilsukarakuzuu** [comment]
I added your .yaml file to our .yaml file and now I am testing. Then I will merge it to main. Right now it looks okay, I will update this later.

**Comment by ahmetfirat23** [comment]
I merged everything to main for production.
