### ISSUE TITLE
Implement routing on the frontend application

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#166]
## Description

We are switching pages with native a tag with href attribute, causing to lose data (i.e. user context) on the frontend application. We need to implement a proper routing mechanism between pages.

We can use [React Router](https://reactrouter.com) for this purpose

***

## Acceptance Criteria
- [ ] React Router is implemented
- [ ] Page transitions are done with Routes with `Link to={}` component or `redirect` function.
<br>...

***

### Reviewer:
This issue will be reviewed by: @e-taha @isilsukarakuzuu

**Comment by ahmetfirat23** [comment]
We already have router. For quick trick we just used href in the game of the day link. I converted it to onclick function. 409d6c2 commit fixes this issue
