### ISSUE TITLE
Adding Authentication Email Sent Feature in backend

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#167]
## Description

We need to ass auth emails for signup. Proper changes need to be done according to that. It needs further research.

We can follow this link [Auth Email Sent](https://stackoverflow.com/questions/63425809/how-to-send-an-authentication-email-in-django)
***

## Acceptance Criteria
- [ ] Authentication emails are sent successfully.
- [ ] Proper managements are done after this change.
- [ ] This feature is tested.
<br>...

***

### Reviewer:
This issue will be reviewed by: @asyasusen @e-taha

**Comment by sonerkuyar** [comment]
closing old course issue.
