### ISSUE TITLE
Add Game of Day property to Backend 

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#168]
## Description

For the game Page wrote a query and backend endpoint to extract genres, publishers, platform, country infos(attributes  can get broaden). 

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
SELECT DISTINCT ?gameLabel
WHERE {
  ?game wdt:P31 wd:Q7889; # Video game instance
        rdfs:label ?gameLabel.
  FILTER(LANG(?gameLabel) = "en").
}
ORDER BY RAND()
LIMIT 1

this query selects a random game name, it is a bit slow but it should be run once per day so i dont think it should be huge a problem. please review before using it might be buggy.

**Comment by sonerkuyar** [comment]
Let's keep it for the final milestone. I dont want to break the code.

**Comment by ahmetfirat23** [comment]
This issue is complete sorry I forgot to close it.
