### ISSUE TITLE
Add Game of Day Property to Frontend

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#169]
## Description

Wrote a function to fetch the game of day property (asynchronously) from the backend. When it's clicked to the Game of the day, fetch the data and show under the game. Making design of its card.
***

### Reviewer:
This issue will be reviewed by:  @asyasusen

**Comment by sonerkuyar** [comment]
Due to @asyasusen has no feedback and we tested the code I'm closing the issue .

**Comment by asyasusen** [comment]
> Due to @asyasusen has no feedback and we tested the code I'm closing the issue .

Next time can you put the issue into review needed or tag me saying you are done so that I can test it? I've looked at it now everything seems fine
