### ISSUE TITLE
Update RAM for Backend and Deployment

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#174]
## Description

Backend and deployment sections of RAM should be more detailed.

***

### Reviewer:
This issue will be reviewed by: _@sonerkuyar_

**Comment by ahmetfirat23** [comment]
I updated these parts @sonerkuyar please feel free to check if I remember some part incorrectly and feel free to close the issue

**Comment by sonerkuyar** [comment]
It looks okey I'm closing the issue.
