### ISSUE TITLE
Write/Check Installation Guides

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#175]
## Description

I am not sure whether we have the installation guide that instructor and TAs can use to run our app locally. Please check if we have. If we don't write one. Also we have separate guides some of them generated automatically. Please clarify them.

***

## Acceptance Criteria
- [x] Backend installation checked
- [x] Frontend installation checked
- [x] Mobile installation checked
- [x] Overall installation guide is written
<br>...

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by isilsukarakuzuu** [comment]
I wrote backend installation guide. I see some changes are made in that, I double checked them. It looks good.

**Comment by isilsukarakuzuu** [comment]
> > I wrote backend installation guide. I see some changes are made in that, I double checked them. It looks good.
> 
> Hey where are we putting the guides that we wrote

I opened a readme inside of backend and wrote it there, should we write it also to wiki?

**Comment by asyasusen** [comment]
I've added the installation guide to frontend-dev branch in README.md file

**Comment by ahmetfirat23** [comment]
Can you upload it to dev

**Comment by ounuvar** [comment]
We already have a README installation guide for the mobile app under the app/mobile/Playlog directory on the mobile-dev branch @ahmetfirat23

**Comment by ahmetfirat23** [comment]
my bad thanks for pointing out
