### ISSUE TITLE
Updating Local/Online Deployment Tutorials

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#184]
## Description

I have written a guide for online deployment on Milestone report. Can you please include that in the project repository too? Also our local deployment guide need fixation for endpoint address and should be replaced.

**Comment by isilsukarakuzuu** [comment]
Let's make comprehensive changes after this milestone at #185 , for now I will update dev and I will add tutorial how to run locally using dev branch.

**Comment by isilsukarakuzuu** [comment]
I did it. Can you please check [here](https://github.com/bounswe/bounswe2024group12/blob/main/README.md)?

**Comment by ahmetfirat23** [comment]
lgtm
