### ISSUE TITLE
Implement property page

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#186]
## Description

Implement property page. It should have info about property and games related to it. The pages design and functionality must be up and running.

***

## Sub-Issues
- [x] #190 
<br>

### Reviewer:
This issue will be reviewed by: _@sonerkuyar_

**Comment by ahmetfirat23** [comment]
Testing server code is here: https://gist.github.com/ahmetfirat23/aa86f2cab2f8153705e19d05d19e390e 
@isilsukarakuzuu @ArdaYalcindag please check this and code the endpoint accordingly.

**Comment by isilsukarakuzuu** [comment]
I added a [sub-issue](https://github.com/bounswe/bounswe2024group12/issues/190) for endpoint @ahmetfirat23

**Comment by ahmetfirat23** [comment]
@sonerkuyar please check the pull request

**Comment by ahmetfirat23** [comment]
We have shown property page in demo so I think this issue is solved.
