### ISSUE TITLE
Add tokens for logged in user

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#192]
## Description

Add tokens for logged in user and check token validity in only logged-in user operations.

***

## Acceptance Criteria
- [ ] Token feature is added.
- [ ] Token feature is tested.
- [ ] Token required (only logged-in user operations) endpoints are updated with token check.
- [ ] Token required endpoints are tested.
<br>

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by isilsukarakuzuu** [comment]
@ahmetfirat23 as we talked before, we will implement this after Milestone 4, so I'm lowering the priority.

**Comment by sonerkuyar** [comment]
closing old course issue
