### ISSUE TITLE
"Guest" User in backend

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#194]
## Description

Due to some certain design choices I am using "Guest" username to check user whether sign in or not in some places. To make my life a little bit easier I need no user to be able to sign up with "Guest" username. Please either create a dummy user named "Guest" directly from database or directly reject the name in the sign up function by saying user already exists. I would prefer the latter because a dummy user might create overhead and extra checks but the choice up to you. Please let me know which way you choose urgently.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by isilsukarakuzuu** [comment]
Ok, we can reject it directly.

**Comment by isilsukarakuzuu** [comment]
Does case-sensitiveness matter? @ahmetfirat23
