### ISSUE TITLE
Implement 404 Page

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#195]
## Description

Implement a simple 404 page that has buttons to redirect main page and return back.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by ahmetfirat23** [comment]
I remembered there is an invalid access card in common file which has the same function. We can use that as 404 page; however, can you please check whether return back functionality is trivial to implement. If it is please implement, otherwise close this issue as not planned. @asyasusen

**Comment by asyasusen** [comment]
> n you please check whether return back functionality is trivial to implement.

I didn't exactly understand what do you mean by return back functionality. Also when will there be a 404 page? I was thinking if a game page didn't load we can just write error loading the game. I didn't implement the invalid access card so I'm not sure what you want me to check

**Comment by ahmetfirat23** [comment]
> I didn't exactly understand what do you mean by return back functionality. Also when will there be a 404 page? I was thinking if a game page didn't load we can just write error loading the game. I didn't implement the invalid access card so I'm not sure what you want me to check

A lot of times actually. I was asking about go to last page you opened before falling into 404 page however let's not deal with that. Every wrong url leads to 404 which is invalid access card.
