### ISSUE TITLE
Implement Edit Profile Page

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#196]
## Description

Implement an edit profile page. This page should follow the requirements described. Please feel free to include anything that I forgot.

***

## Acceptance Criteria
- [ ] User shall change their profile picture
- [ ] User shall change their favorite properties and should change which five property will be shown in the page. User should be able to select less than 5 property.
- [ ] User shall change their favorite games. User shall be able to select up to five games.

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_, _@isilsukarakuzuu_

**Comment by sonerkuyar** [comment]
I'm not sure about How I can finish this task. Fuzzy Search will take more time than I thought. If anyone want to attend this feature, can attend. @asyasusen @ahmetfirat23 @yusufaygun

**Comment by sonerkuyar** [comment]
Closing old course issue.
