### ISSUE TITLE
Implement Review Endpoint

### ISSUE THREAD

**Issue by ArdaYalcindag** [bounswe/bounswe2024group12#200]
## Description

Add endpoint for reviews.

***

## Acceptance Criteria
- [x] Implement review table
- [x] Implemented review writing endpoint.
- [x] Implement review edit and delete endpoint.
- [x] Implement review liking endpoint.
- [x] Implement review listing endpoints.
- [x] Tested review endpoint.
- [ ] Unit tests are written.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
I added the extra tasks we talked about. Table and endpoint looks OK but are you sure the like count starts from zero when you do not initialize to anything? That might be a problem. Also please open a branch and connect it to this issue so we don't have conflict problems.

**Comment by ArdaYalcindag** [comment]
OK, I have opened a new branch. Also like count starts from zero now.

**Comment by ahmetfirat23** [comment]
cool, also please be aware that lastEditDate might not work as you consider and require extra handling. please refer to documentation:

  DateField.auto_now[¶](https://docs.djangoproject.com/en/5.0/ref/models/fields/#django.db.models.DateField.auto_now)
  Automatically set the field to now every time the object is saved. Useful for “last-modified” timestamps. Note that the current date is always used; it’s not just a default value that you can override.
  
  The field is only automatically updated when calling [Model.save()](https://docs.djangoproject.com/en/5.0/ref/models/instances/#django.db.models.Model.save). The field isn’t updated when making updates to other fields in other ways such as [QuerySet.update()](https://docs.djangoproject.com/en/5.0/ref/models/querysets/#django.db.models.query.QuerySet.update), though you can specify a custom value for the field in an update like that.

**Comment by ArdaYalcindag** [comment]
Can you check the editReview function as well. I think lastEdit is updated as intended when a review is edited.

**Comment by ArdaYalcindag** [comment]
Finished endpoints. Only testing phase left.

**Comment by ahmetfirat23** [comment]
There was some missing points in the review functions. I fixed them for unit tests you may open a new issue. I tested functions manually they are working fine.

**Comment by ahmetfirat23** [comment]
Well we saw manual tests are not as good as testing it on the deployment. I had a rough time get it up and running but with @isilsukarakuzuu 's help it worked on demo. nice.
