### ISSUE TITLE
Implement Main-Page Endpoints

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#203]
## Description

Implement main-page endpoints, game-of-the-day, new-games, popular-games, all-games. They should return game names with their slug.

***

## Acceptance Criteria
- [x] game-of-the-day endpoint is implemented.
- [x] new-game is implemented.
- [x] popular-games is implemented.
- [x] all-games is implemented.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23 @asyasusen

**Comment by isilsukarakuzuu** [comment]
I implemented these endpoints. Please check Postman Workspace for usage.

**Comment by ahmetfirat23** [comment]
#202 closes this issue
