### ISSUE TITLE
Test Main-Page Endpoints

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#204]
## Description

Test main-page endpoints, game-of-the-day, new-games, popular-games, all-games with different scenarios.

***

## Acceptance Criteria
- [ ] game-of-the-day endpoint is tested.
- [ ] new-game is tested.
- [ ] popular-games is tested.
- [ ] all-games is tested.
<br>

***

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu

**Comment by isilsukarakuzuu** [comment]
@ahmetfirat23 @yusufaygun @ArdaYalcindag @mbatuhancok Can some of you test these endpoints?

**Comment by ahmetfirat23** [comment]
I thought this issue was about unit tests. Did we complete this issue @isilsukarakuzuu
