### ISSUE TITLE
Document Meeting 1 Report (Lab)

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#251]
## Description

Document meeting notes from Lab.

***

## Acceptance Criteria
- [x] Put the meeting notes under wiki with the structure from 351 course template
- [x] Write a lab report from meeting notes.

**Comment by ArdaYalcindag** [comment]
Written [meeting note #1](https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%231-%E2%80%90-25.09.2024) and added it into main wiki page and sidebar.

**Comment by sonerkuyar** [comment]
As I see this issue is complete now. I'm closing.
