### ISSUE TITLE
Organizing Personal Pages

### ISSUE THREAD

**Issue by ArdaYalcindag** [bounswe/bounswe2024group12#252]
## Description

Everyone needs to organize their personal page and put it into the wiki.

***

## Acceptance Criteria
- [x] Ahmet Firat Gamsiz
- [ ] Arda Yalcindag
- [x] Isil Su Karakuzu
- [x] Orhan Unuvar
- [x] Ozan Kaymak
- [x] Soner Kuyar
- [ ] Taha Ensar Kukul
- [x] Yusuf Aygun

**Comment by ArdaYalcindag** [comment]
Should we create new personal pages or create a different section for this semester's weekly effort in our existing personal page? What do you think?

**Comment by ozankaymak** [comment]
I already created my personal page right next to what you guys had. Lmk if you're going to use new ones.

**Comment by ahmetfirat23** [comment]
I think putting old weekly work section under something like 352 weekly work header and updating personal information if anything changed in your life should be sufficient. What to call the header depends on the first person who decides to finish this task imho .d

**Comment by isilsukarakuzuu** [comment]
I finished my part, I did it like that: [Isil Su Karakuzu](https://github.com/bounswe/bounswe2024group12/wiki/Isil-Su-Karakuzu) 
If you think that's ok, we can follow this

**Comment by yusufaygun** [comment]
I organized my page similar to Işıl's page: [Yusuf Aygun](https://github.com/bounswe/bounswe2024group12/wiki/Yusuf-Aygun)

**Comment by ozankaymak** [comment]
I did it too: [Ozan Kaymak](https://github.com/bounswe/bounswe2024group12/wiki/Ozan-Kaymak)

**Comment by ahmetfirat23** [comment]
I updated [mine](https://github.com/bounswe/bounswe2024group12/wiki/Ahmet-Firat-Gamsiz) too. Also, can someone update this issue to include the Who We Are page in an appropriate place in the sidebar?

**Comment by ounuvar** [comment]
I also updated my personal page.

@ahmetfirat23 Do you mean include all our personal pages under a Who We Are section in the sidebar?

**Comment by ahmetfirat23** [comment]
Kinda yes, they are under the 352 section rn, we should carry them out of there
> @ahmetfirat23 Do you mean include all our personal pages under a Who We Are section in the sidebar?

**Comment by ahmetfirat23** [comment]
Kinda yes, they are under the 352 section rn, we should carry them out of there
> @ahmetfirat23 Do you mean include all our personal pages under a Who We Are section in the sidebar?

**Comment by ahmetfirat23** [comment]
Kinda yes, they are under the 352 section rn, we should carry them out ıf there
> @ahmetfirat23 Do you mean include all our personal pages under a Who We Are section in the sidebar?

**Comment by ounuvar** [comment]
Ah I see. Okay I'm creating a separate issue for this

**Comment by ahmetfirat23** [comment]
Since Arda and Talha won't be continuing I think this task is complete. However, there is no reviewer assigned. Can somebody please take a quick look over pages and make sure everything is in place.

**Comment by ounuvar** [comment]
@ahmetfirat23 everyone's except Arda's and Taha's look fine. I'm removing their pages from the sidebar as well. We can close the issue.
