### ISSUE TITLE
Add communication plan

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#253]
## Description

We decided on the communication plan in the last meeting. However, we haven't added it to the wiki yet. Please make a page similar to the one from the previous course.

***

## Acceptance Criteria
- [x] Create a communication plan page
- [x] Add the link to the sidebar

***

### Reviewer:
This issue will be reviewed by: _@ahmetfirat23_

**Comment by isilsukarakuzuu** [comment]
added, you can check it here: [Communication Plan for CMPE451](https://github.com/bounswe/bounswe2024group12/wiki/Communication-Plan-for-CMPE451)

**Comment by ahmetfirat23** [comment]
lgtm thanks
