### ISSUE TITLE
Add Meeting #3 Notes to the Wiki

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#255]
## Description

Notes for Meeting 3 (Oct 1) should be added to the Wiki.

**Comment by ahmetfirat23** [comment]
Hi, here is the meeting notes sorry for the delay: https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%233-%E2%80%90-01.10.2024

**Comment by ahmetfirat23** [comment]
please let me know if i forgot to include something

**Comment by ahmetfirat23** [comment]
> @ahmetfirat23 Can we add the meeting notes to the homepage as well?

done
