### ISSUE TITLE
Prepare Requirements for the Project

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#256]
## Description

We should write and check our requirements for this project.

***

## Acceptance Criteria
- [x] Requirements are written.
- [x] Requirements are checked.
<br>...

***

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu @sonerkuyar @yusufaygun

**Comment by ahmetfirat23** [comment]
I will check the last draft, propose changes if necessary.

**Comment by ahmetfirat23** [comment]
I made some comments and suggested some changes to the requirements. Can you please take a look at them @ounuvar @ozankaymak ? Also, we were supposed to add different user types, but I didn't see any mentions. Should I add that myself, or should we discuss it in the next lab? Also, we need to write our elicitation questions, which may need to have its own issue.

**Comment by ounuvar** [comment]
I've completed the requirements document and added it to the wiki. You can find it in the sidebar. Elicitation questions can be discussed under the elicitation issue.
