### ISSUE TITLE
Initialize Backend with Django

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#259]
## Description

We should initialize our Backend codebase using Django.

***

## Acceptance Criteria
- [x] A codebase for Backend is initialized.
- [x] Backend part of the project has the correct file structure and hierarchy in the project.
<br>

***

### Reviewer:
This issue will be reviewed by: _reviewers needed_

**Comment by sonerkuyar** [comment]
I created backend project, added a readme file to build-run. 
Organized file structure and endpoint addresses by versioning api/v1/<app_name>
[related commit](https://github.com/bounswe/bounswe2024group12/commit/563a7a8772b18c8953645dbd6c7faf71198fe138).
I'm closing the issue.
