### ISSUE TITLE
Create a Database System with MySQL

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#261]
## Description

We should create a database system with MySQL in Django.

***

## Acceptance Criteria
- [x] Database is created.
- [x] Database is working without errors.
<br>

***

### Reviewer:
This issue will be reviewed by: _reviewers needed_

**Comment by sonerkuyar** [comment]
I created mysql database and configured the Django app with database settings. 
Also, created a healthcheck pipeline in docker file. 
I'm closing the issue.
