### ISSUE TITLE
Create Scenarios for the Project

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#264]
## Description

We should write scenarios to check and track our project's usage from a user's view.

***

## Acceptance Criteria
- [x] 5 scenarios for the project are created.
- [x] Designs from related mockups are added to the scenarios.
- [x] All scenarios is reviewed by the team.
- [x] All scenarios are added to wiki.
<br>

***

### Reviewer:
This issue will be reviewed by: @ounuvar @ozankaymak @ahmetfirat23

**Comment by isilsukarakuzuu** [comment]
@sonerkuyar @yusufaygun how is this issue going? are all scenarios done and only thing left is adding mockup pages? Im working on mockups rn

**Comment by yusufaygun** [comment]
I fixed scenarios 1 and 3 according to finalized requirements, also created a new scenario and added it as scenario 5.
