### ISSUE TITLE
Prapering Github Project On Projects Tab

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#272]
## Description
There is a need to create new Github Project to organize project issues, plan and timeline. 

***

## Acceptance Criteria
- [x] Createing Major Activities
- [x] Creating Milestones for Project
- [x] Preaparing Timeline
<br>

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
LGTM. We need to start using start and end date features under project to make the tasks appear in timeline.
