### ISSUE TITLE
Create RAM

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#273]
## Description

Creating RAM (responsibility assignment matrix) similar to last semester. 

***

## Acceptance Criteria
- [x] RAM Created similar to CMPE352 

<br>...

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
LGTM @isilsukarakuzuu can we add our responsibilities to ram?
