### ISSUE TITLE
Create Sequence Diagrams

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#279]
## Description

We should create sequence diagrams for our project.
***

## Acceptance Criteria
- [x] Sequence diagrams are created.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23 @ounuvar

**Comment by ozankaymak** [comment]
@isilsukarakuzuu can you take a look at my initial Sequence Draft document?

**Comment by isilsukarakuzuu** [comment]
thanks @ozankaymak lgtm
