### ISSUE TITLE
Define Endpoints for Milestone1 

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#284]
## Description

Creating endpoints definitions for milestone 1 which are apps for accounts (login-signup-authenticate-access users) and posts (creating post- getting post - assigning related user).  

***

## Acceptance Criteria
- [x] Creating accounts app and define its endpoints
- [x] Creating posts app and define its endpoints
- [x] Documentate endpoints at swagger
<br>

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu @ozankaymak

**Comment by yusufaygun** [comment]
We created the necessary endpoints and documented them with swagger: [167.99.133.190/swagger](https://167.99.133.190/swagger)
