### ISSUE TITLE
Implement Logic of Posts App

### ISSUE THREAD

**Issue by yusufaygun** [bounswe/bounswe2024group12#285]
## Description

We should implement the logic of posts app and make sure that all endpoints are working smoothly and as intended.

***

## Acceptance Criteria
- [x] Define necessary endpoints and data fields for posts app
- [x] Implement the logic of endpoints
- [x] Make necessary controls in endpoints like authentication, authorization, data format etc.

***

### Reviewer:
This issue will be reviewed by: @sonerkuyar

**Comment by sonerkuyar** [comment]
LGTM!
