### ISSUE TITLE
Implement Post Functionality

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#286]
## Description

This task includes implementing post functionality. User should be able to share posts with header, text, single image, single fen notation (display as chess table) and tags.

***

## Acceptance Criteria
- [x] Header and text box and data logic implemented.
- [x] Image upload and data logic implemented.
- [x] Fen notation, rendering and data logic implemented.
- [x] Tag selection implemented.
- [x] Formatting the post and sending to backend implemented.
<br>

***

### Reviewer:
This issue will be reviewed by: _@isilsukarakuzuu_

**Comment by ahmetfirat23** [comment]
completed, please check ed67c38cb2613c36d650019d8b96adb23190c21c
i left pgn file upload for later, also i don't check for the file format rn

**Comment by isilsukarakuzuu** [comment]
there was a issue about title data, temporarily fixed it, fyi
