### ISSUE TITLE
Implement Feed Functionality

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#287]
## Description

Implement raw feed functionality. Currently feed should retrieve all posts and display.

***

## Acceptance Criteria
- [x] Implement post retrieval mechanism.
- [x] Implement post displaying mechanism.
<br>

***

### Reviewer:
This issue will be reviewed by: _@isilsukarakuzuu_

**Comment by isilsukarakuzuu** [comment]
I also added guest user and logged in difference in feed, also pagination, lgtm
