### ISSUE TITLE
Implement FEN rendering

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#288]
## Description

Implement FEN rendering logic with chessboard.js. This task may require converting project to typescript if chessboard.js enforce it.

***

## Acceptance Criteria
- [x] Parse FEN notation
- [x] Render it and display
<br>

***

### Reviewer:
This issue will be reviewed by: _@isilsukarakuzuu_

**Comment by ahmetfirat23** [comment]
completed, please check 08e433ee15bef2e970724063087d0001da434cf3

**Comment by isilsukarakuzuu** [comment]
lgtm, merged it
