### ISSUE TITLE
Implement Authorization Logic

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#291]
## Description

To recognize user in user based backend operation authentication 

***

## Acceptance Criteria
- [x] Login - Signup and their models should be implemented
- [x] JWT token based authorization for endpoints should be added
- [x] Management of lifetimes and reliability of Access tokens should be fixed
<br>...

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by yusufaygun** [comment]
Everything looks fine, I am closing this issue.
