### ISSUE TITLE
Creating Setup Instructions for Backend

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#293]
## Description

For pre-relase setup Instructions create a draft for Readme.md and complete the backend Instructions part.

***

## Acceptance Criteria
- [ ] Backend and db local deployments part works at a clean machine
- [ ] Indicate the PORTS which Backend works to use by frontend.
<br>...

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu

**Comment by sonerkuyar** [comment]
I added backend part also created a reserve spaces for mobile and fronted at this [commit](https://github.com/bounswe/bounswe2024group12/commit/66228c52b3a16fef75f635ebf619c29ba18f8bac)
@isilsukarakuzuu @ounuvar

**Comment by isilsukarakuzuu** [comment]
I added frontend part, fyi

**Comment by sonerkuyar** [comment]
It completed I'm closing the issue
