### ISSUE TITLE
Deployment of Frontend

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#298]
## Description
Taking the pre-relase tagged code from main branch and deploy at digital ocean

***

## Acceptance Criteria
- [x] React app should be accessible by https://167.99.133.190:3000/

<br>

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu @ahmetfirat23

**Comment by sonerkuyar** [comment]
There is an issue still with related to secure connection but react app available at http://167.99.133.190:3000/

**Comment by ahmetfirat23** [comment]
sry i forgot to close this issue, we were all able to access the link.
