### ISSUE TITLE
Create Comment and Like related endpoints

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#315]
## Description
Adding comment, like and getting the status of posts in terms the like and comments

***

## Acceptance Criteria
- [x] Like/Unlike Post successfully.
- [x] Add comment, edit and delete existing ones successfully.
- [x] Get like number - status and comments of posts.
<br>...

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
[Related Commit](https://github.com/bounswe/bounswe2024group12/commit/1ca7ad2e6d32307275da6ba9fa05c847621d1d33l)
I've completed the task.

**Comment by yusufaygun** [comment]
lgtm.
