### ISSUE TITLE
Research and Try for Chess Game Database

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#316]
## Description

To show at our app we need a chess game database, which we can use at our app for archive games.

***

## Acceptance Criteria
- [x] Finding an applicable database.
- [x] Games are fetchable successfully.
- [x] Deciding how to adapt original backend database ,creating a structure

! Acceptance criteria changed because I decided to create our own database #318 

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by yusufaygun** [comment]
Completed, I am closing this issue.
