### ISSUE TITLE
Collect Data and Create Games Table

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#318]
## Description

Due to the complications at #316 about accessing an open database with extensive search and filtering options, it is necessary to create our own database and implement filter options.

## Acceptance Criteria
- [x] Collect sufficient data to create a table for Archive feature of app.
- [x] Process collected data and write to database appropriately.

### Reviewer:
This issue will be reviewed by: @yusufaygun @ahmetfirat23

**Comment by sonerkuyar** [comment]
I completed this issue you can see at these commits:
 [Unification of PGNs and Download files](https://github.com/bounswe/bounswe2024group12/blob/375d05ec5c024ca8f27e591860781607a05de9f8/app/backend/ipynbs/download_matches.ipynb)
 [Create database and import from jsonfile](https://github.com/bounswe/bounswe2024group12/commit/b3f162007cdf5ffb7736341d2c34c2f81c8650cd)

**Comment by yusufaygun** [comment]
Everything seems fine, the database is working correctly. I am closing this issue.
