### ISSUE TITLE
Implement extensive filter for game search 

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#319]
## Description

Write the description of the task. Description should express what exactly needs to be done rather than general statements.

***

## Acceptance Criteria
- [x] Client should be able to filter games by date.
- [x] Client should be able to filter games by player name.
- [x] Client should be able to filter games by game result. 
- [x] Client should be able to filter games by cite. 
- [x] Client should be able to filter games by event name. 

### Reviewer:
This issue will be reviewed by: @yusufaygun @isilsukarakuzuu

**Comment by isilsukarakuzuu** [comment]
lgtm, already used it!! :D
