### ISSUE TITLE
Add Endpoints for Game Comments

### ISSUE THREAD

**Issue by yusufaygun** [bounswe/bounswe2024group12#323]
## Description

Create endpoints that allow users to comment on specific moves (or positions) of a game. Each comment should include the following details:

- The user's username
- The FEN notation of the commented position
- The comment text
- Additional FENs referenced in the comment (optional)
- The game ID

Ensure proper database design and include endpoints for both creating and retrieving these comments.
***

## Acceptance Criteria
- [x] The `GameComment` model is created with the specified fields and proper database design.
- [x] An endpoint for adding comments to a specific move of a game is implemented and tested.
- [x] An endpoint for retrieving all comments related to a specific game is implemented and tested.

***

### Reviewer:
This issue will be reviewed by: @sonerkuyar

**Comment by isilsukarakuzuu** [comment]
@sonerkuyar we talked about this together so I'm closing this now
