### ISSUE TITLE
Implement Commenting System Per Move Per Game (With Backend Integration)

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#325]
## Description
Fetch and display comments for each move of a game from the backend. Ensure new comments are added and displayed immediately after submission.

***
## Acceptance Criteria
- [x] Fetch and display comments for each move per game.
- [x] Add and display new comments immediately after submission.
***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
resolved by #324
