### ISSUE TITLE
Implement Advanced Game Search (With Backend Integration)

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#326]
## Description
Allow users to search games by event, player names, date, or result. Connect the search form to the backend to filter and return relevant results.

***
## Acceptance Criteria
- [x] Implement search filters for event, player names, date, and result.
- [x] Connect the form to the backend for filtered results.
- [x] Display accurate search results based on user input.
- [x] Make results clickable.

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
resolved by #324
