### ISSUE TITLE
Convert PGN to FEN Notation

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#327]
## Description
Convert PGN data to FEN notation to show the chessboard position for each move. Include relevant metadata such as player names and event details.

***
## Acceptance Criteria
- [x] Convert PGN to FEN for each move.
- [x] Display the correct chessboard position after each move.
- [x] Parse and show relevant metadata (players, event, result).

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
resolved by #324
