### ISSUE TITLE
Enable Step-by-Step Game Navigation (With Backend Integration)

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#328]
## Description
Allow users to navigate through game moves, displaying the FEN position for each move. Ensure the frontend syncs with the backend to show move data.

***
## Acceptance Criteria
- [x] Users can navigate between game moves correctly.
- [x] Display the chessboard position using FEN notation from real data.
- [x] Sync move data with the backend correctly.

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by ahmetfirat23** [comment]
resolved
