### ISSUE TITLE
Explore Games Endpoint

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#330]
## Description

An endpoint will be created which will take current position info and filters then it will return statistics of official games at that position and also 10 top rated official game id. 

***

## Acceptance Criteria
- [x] Endpoint successfully returns the statistics about the root position of the game. 
- [x] Endpoint successfully returns the top 10 rated official game links.

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by yusufaygun** [comment]
Endpoint works fine, I am closing this issue.
