### ISSUE TITLE
Create Master Game Endpoint

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#331]
## Description

Endpoint to take the PGN of games which we found at the #330 endpoint.

***

## Acceptance Criteria
- [x] Based on game_id endpoint returns the PGN of official game. 

This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
[Related Commit](https://github.com/bounswe/bounswe2024group12/pull/335/commits/103080e5ff79fd72b819d81331a55d38732b4572)
I've completed it.

**Comment by yusufaygun** [comment]
Endpoint works fine, I am closing this issue.
