### ISSUE TITLE
Create an endpoint to filter games

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#332]
## Description

An endpoint will provides extensive filtering over our local game database.

***

## Acceptance Criteria
- [x] Players can be searched by case-insensitive search. 
- [x] Site of match can be searched by case-insensitive search. 
- [x] Event name of match can be searched by case-insensitive search. 
- [x] Game can be searched by year filtering.

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
[Related commit](https://github.com/bounswe/bounswe2024group12/pull/335/commits/103080e5ff79fd72b819d81331a55d38732b4572)
I've completed

**Comment by yusufaygun** [comment]
Endpoint works fine, I am closing this issue.
