### ISSUE TITLE
Deploy Frontend

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#345]
## Description

Arrange environment for frontend ad deploy the frontend app

***

## Acceptance Criteria
- [x] Frontend app is accesible without an error at [here](https://buchessocial.online)

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by sonerkuyar** [comment]
As we presented at the Demo I deployed the frontend app successfully.

**Comment by ahmetfirat23** [comment]
the page is up sorry for the delay
