### ISSUE TITLE
Backend: Implement Fetching Puzzles feature

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#365]
## Description

To show the puzzles at app's, backend api should return the puzzles to the client app.

***

## Acceptance Criteria
- [x] Daily Puzzle are returned successfully from backend.
- [x] Random Puzzles are returned successfully from backend.
- [x] Puzzles are returned by filtering successfully from backend.
- [x] Endpoint Documentation clearly explained with examples
- [x] Unit Test For the endpoint has been created. 
<br>...

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by yusufaygun** [comment]
Everything seems fine, I checked the PR and tests also work successfully. Closing the issue.
