### ISSUE TITLE
Backend: Enhance List post items endpoint

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#369]
## Description

Listing feed post endpoints should be improved in terms of ordering, filtering and easy access to ease client to fetch posts effectively.

***

## Acceptance Criteria
- [x] Posts are ordered by given field from frontend (default is date).
- [x] Posts will be filterable according to tags.
- [x] Endpoint documented with examples
- [x] Test for endpoint is wrote and run successfully.

### Reviewer:
This issue will be reviewed by: @yusufaygun @isilsukarakuzuu

**Comment by yusufaygun** [comment]
All things look good to me, issue can be closed.
