### ISSUE TITLE
Backend: Create Follow/Unfollow User Endpoint

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#370]
## Description
Endpoint should be created to provide users to follow/unfollow other users functionality.

***

## Acceptance Criteria
- [x] Only Authenticated user able to  follow other users.
- [x] User can't follow itself.
- [x] Endpoint is documented with examples.
- [x] Test for the endpoint wrote and run successfully.
<br>...

### Reviewer:
This issue will be reviewed by: @sonerkuyar

**Comment by yusufaygun** [comment]
Tasks related to this issue have been completed.
- The toggle follow/unfollow endpoint has been implemented to allow users to follow or unfollow others.
- Only authenticated users can follow/unfollow other users, ensuring proper access control.
- Users are prevented from following themselves.
- Swagger documentation has been added for the endpoint, including request/response examples.
- Comprehensive unit tests have been written and successfully executed to validate the endpoint's functionality.

You can see all the changes here: #382

**Comment by sonerkuyar** [comment]
LGTM!
