### ISSUE TITLE
Backend: Create Backend Structure for Annotations

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#373]
## Description
Endpoint will be created to keep the annotations at backend with their corresponding fields, database structure and references will be revisited to implement functionality

***

## Acceptance Criteria
- [x] Annotations can be inserted/got from database successfully, with appropriate users.
- [x] Database structure is compatible to add annotations to any entity.
- [x] Endpoints for annotations are well documented with examples.
- [x] Tests are implemented and run for endpoints with test cases.

### Reviewer:
This issue will be reviewed by: @ahmetfirat23

**Comment by yusufaygun** [comment]
- Implemented CRUD operations for annotations with proper database structure and UUID identifiers.
- Ensured compatibility with Web Annotation Data Model.
- Added Swagger documentation with detailed request/response examples.
- Developed and executed unit/integration tests covering success, failure, and permission scenarios.

Details are in linked PR's descriptions.
