### ISSUE TITLE
Backend: Create User Page Endpoints

### ISSUE THREAD

**Issue by yusufaygun** [bounswe/bounswe2024group12#377]
## Description

Necessary endpoints should be created to provide entities in user page such as bookmarks, likes and followers.

***

## Acceptance Criteria
- [x] Endpoint for current user's profile page is created, it returns user's info including bookmarks, likes, followers, following, posts etc.
- [x] Endpoint for other user's profile page is created, it returns everything the previous endpoint returns except the bookmarks.
- [x] Endpoints are documented with examples.
- [x] Tests for the endpoints created and ran successfully.

***

### Reviewer:
This issue will be reviewed by: @sonerkuyar

**Comment by yusufaygun** [comment]
- Endpoints are created 
- The /api/v1/accounts/me/ endpoint is accessible only to authenticated users.
- Swagger documentation has been added for both endpoints, with request/response examples and parameter details.
- Comprehensive unit tests have been written and successfully executed to validate the endpoints' functionality.

Related PR: #385

**Comment by sonerkuyar** [comment]
User page endpoints are working correctly.
