### ISSUE TITLE
Backend: Fix the try it out bug at deployment

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#393]
## Description
Endpoint couldn't be tried via swagger UI at the deployment. There is no issue at the localhost build. It's broken only at the development server. Here is the screenshot.
<img width="1401" alt="Screenshot 2024-12-14 at 17 45 35" src="https://github.com/user-attachments/assets/73e5a678-015b-4868-89e6-6e26c4f62ccb" />

***

## Acceptance Criteria
- [x] Endpoints can be tried via development server by following their documentation

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
I solved the bug 2 days ago and informed teammates via channel, changes I've made at the deployment part:
 by adding 
`CORS_ALLOW_HEADERS = [
    'authorization',
    'content-type',
    'x-csrftoken',
    'accept',
    'accept-encoding',
]`
Also at the top level, used https scheme and deployment url.
Now the endpoints can be called via swagger UI. 

https://github.com/user-attachments/assets/a9a0bb97-84ff-4066-bc21-1c3eb9e21036

**Comment by yusufaygun** [comment]
The bug seems to be fixed, nice work. I am closing the issue.
