### ISSUE TITLE
Backend: Create Tournaments Endpoints

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#396]
## Description

Due to we've done nothing about the tournaments some endpoints could be created and  process the responses and add easy to implementable endpoints for clients app

***

## Acceptance Criteria
- [x] Get current tournaments
- [x] Parse and Return the games at the rounds of tournament
- [x] Document with examples at swagger 
- [x] Unit test created and run successfully
<br>...

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
Completed the issue at #397 PR. Detailed explanations also under the PR description and commit descriptions.

**Comment by yusufaygun** [comment]
PR looks fine and I already reviewed it. Closing the issue.
