### ISSUE TITLE
Database: Add deployment dataset into final product

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#399]
## Description
At the final product we also need to insert our current database which consist of 28K chess games 80 openings and 100 user posts as a deliverable. User posts should be created via artificial tools or in-person. Then current status of db should be dumped, docker files configured, and instructions for the first build should be added to readme.md

***

## Acceptance Criteria
- [x] At least 100 user posts exist at database.
- [x] Irrelevant data cleared from database.
- [x] Instructions wrote in Readme.md 

### Reviewer:
This issue will be reviewed by: @ozankaymak @yusufaygun

**Comment by sonerkuyar** [comment]
I've created additional database via LLM tools. 
Wrote script to write database and took a snapshot of database.
Updated Readme to build backend-db app. 
#410 this issue arises.
You can check linked PR.

**Comment by yusufaygun** [comment]
LGTM.
