### ISSUE TITLE
Backend: Solve backend init before db healthy

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#410]
## Description

The Django backend container attempts to connect to the MySQL database before the database initialization process is fully complete, causing the following error:
`django.db.utils.OperationalError: (2002, “Can’t connect to server on ‘db’ (115)”)`
This occurs because `depends_on` in `docker-compose.yml` ensures that the database container starts first but does not wait for the MySQL service to be fully ready to accept connections.
This bug needs to be handled

## Steps to Reproduce
1. Run `docker-compose up`.
2. Observe that the backend fails with an `OperationalError`.
3. Restarting the backend container resolves the issue, as the database is fully initialized by then.

***

## Acceptance Criteria
- [x] No issues while running on a clean machine.
<br>...

### Reviewer:
This issue will be reviewed by: @yusufaygun

**Comment by sonerkuyar** [comment]
I created script before running the backend, you can see at linked PR.
Issue solved.

**Comment by yusufaygun** [comment]
I reviewed the PR, bug is fixed therefore I am closing the issue. Nice work!
