### ISSUE TITLE
Update meeting 1 notes with new template based on lecture feedback

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#48]
Refining [Meeting #1 ‐ 16.02.2024](https://github.com/bounswe/bounswe2024group12/wiki/Meeting-%231-%E2%80%90-16.02.2024) notes with updated titles and added issues based on the new template and lecture feedback. No need to change meeting template since I mentioned it in #47.

**Comment by e-taha** [comment]
Some of them don't have the related issue but other than that it is done.

**Comment by ounuvar** [comment]
We just put a check mark to ones that don't have a corresponding issue (and simple tasks usually don't have a corresponding issue), so it is fine.
