### ISSUE TITLE
Create a Project for  Requirements Elicitation

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#58]
Create a Project for Software Requirements Specification. This Project's outcomes will be a deliverable, so link the related issues to project and  ask teammates to link the newly created issues to the project.

**Comment by isilsukarakuzuu** [comment]
It looks like we need deadlines and a current iteration plan for the project. Currently, all issues are in the backlog. Can you please work on that? @sonerkuyar

**Comment by sonerkuyar** [comment]
As we discussed in the Meeting 6, I changed the Project name to [2024 Group 12 Project](https://github.com/orgs/bounswe/projects/50) and expanded its scope. There will not be one project for each assignment  and we will organize our works depending on iterations and milestones. Also created [Customer Milestone 1](https://github.com/bounswe/bounswe2024group12/milestone/1) for requirements and the other deliverables of first milestone.
