### ISSUE TITLE
Create template pages

### ISSUE THREAD

**Issue by ahmetfirat23** [bounswe/bounswe2024group12#6]
Please create templates for wiki pages that will be either regularly updated or everyone will make an entry. Open a new issue for each task and comment the number of the issue as "#&lt;number&gt;" here. Feel free to update if we need other templates.

- [x] #5  
- [x] #11
- [x] #12
- [x] #13

**Comment by ounuvar** [comment]
I'm separating this issue into multiple issues to make each task more visible.

**Comment by ounuvar** [comment]
I unassigned everyone else except me to keep track of the rest of the issue myself.

**Comment by ounuvar** [comment]
All subissues are completed. Closing the issue.
