### ISSUE TITLE
Reseach and report SPARQL semantic queries and Wikidata API

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#60]
Conduct a research on SPARQL semantic queries and Wikidata API. Write a report for other team members to grasp the concepts. Link references for further reading.

**Comment by ArdaYalcindag** [comment]
Conducted a research about SPARQL and Wikidata API and added my research report to the [Wikidata Research](https://github.com/bounswe/bounswe2024group12/wiki/Wikidata-Research) page.

**Comment by isilsukarakuzuu** [comment]
Can you please add queries and their findings to the Wikidata research document as decided in the extra meeting since it is also required? @ArdaYalcindag @ahmetfirat23

**Comment by ArdaYalcindag** [comment]
We didn't added example queries. Instead we provided useful resources. If needed, we can add some more resources as well. Therefore, I am closing this issue.
