### ISSUE TITLE
Reseach and report Web application development

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#61]
Conduct a research on Web application development. Write a report for other team members to grasp the concepts. Link references for further reading.

**Comment by asyasusen** [comment]
Forgot to add references @sonerkuyar

**Comment by isilsukarakuzuu** [comment]
As we approach the final week before the Milestone 1 deadline, I'm assigning this issue as a high priority, fyi @asyasusen @sonerkuyar It seems like this issue might already be resolved, but I want to double-check. Could you confirm it?

**Comment by sonerkuyar** [comment]
I finalized the web development research page.
