### ISSUE TITLE
Analyze the "Game" domain

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#65]
Analyze the "Game" domain by examining related software systems, document observations of their features, specifically note any missing elements.

**Comment by ahmetfirat23** [comment]
I created a document that has rough outlines and we finalized it with Isil at a face-to-face meeting. Since we showed the most important results of the analysis in the last meeting, we will include the clean copy later on. I am also decreasing the priority to medium.

**Comment by ahmetfirat23** [comment]
I initialised the wiki page, included my part of the report and add the page to sidebar.

**Comment by isilsukarakuzuu** [comment]
I've added my analysis on Letterboxd. Could you please finalize the wiki page and close the issue? @ahmetfirat23

**Comment by ahmetfirat23** [comment]
I included pictures and short sections for steam and igdb i think it is complete.
