### ISSUE TITLE
Write and Conduct Scenarios

### ISSUE THREAD

**Issue by ArdaYalcindag** [bounswe/bounswe2024group12#69]
Open a wiki page for scenarios and write appropriate scenarios according to requirements.

**Comment by ArdaYalcindag** [comment]
Created [Scenario 1](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-1) and added it into the sidebar in the wiki under Scenarios under Practice Project. You can use it as a template for other scenarios as well.

**Comment by yusufaygun** [comment]
Created [Scenario 2](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-2) and added it to the sidebar. Will make some editing about this page to the specified parts, you can take a look.

**Comment by yusufaygun** [comment]
Edited [Scenario 2](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-2). Created [Scenario 4](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-4) and added it to the sidebar. Will make some editing about this page.

**Comment by mbatuhancok** [comment]
Created[ Scenario 3]((https://github.com/bounswe/bounswe2024group12/wiki/Scenario-3) and addet it into the sidebar.

**Comment by sonerkuyar** [comment]
Created [Scenario 5](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-4) and added it to sidebar.

**Comment by yusufaygun** [comment]
Written "Acceptance Criteria" for [Scenario 2](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-2) and [Scenario 4](https://github.com/bounswe/bounswe2024group12/wiki/Scenario-4).

**Comment by yusufaygun** [comment]
All scenarios are done, I am closing the issue
