### ISSUE TITLE
Create communication plan

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#7]
Create a new wiki page for our communication plan and link to it from the wiki homepage.

**Comment by sonerkuyar** [comment]
Communication Plan page created under home page and link added. I got use some initiatives about the unused communication channels. Please let me know if anything should be corrected or added.

**Comment by sonerkuyar** [comment]
Communication Plan page created under home page and link added. I got use some initiatives about the unused communication channels. Please let me know if anything should be corrected or added.
