### ISSUE TITLE
Write Executive summary part of Milestone 1

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#78]
## Description

Compose the Executive Summary for Milestone 1, summarizing the project's progress, achievements and challenges.

***

## Acceptance Criteria
- [x] The Executive Summary accurately summarizes the key points and findings of Milestone 1.
- [x] The Executive Summary has been reviewed for accuracy, clarity, and adherence to formatting or style guidelines outlined for the project.
<br>

***

### Reviewer:
This issue will be reviewed by: @ounuvar @isilsukarakuzuu

**Comment by ArdaYalcindag** [comment]
Written a summary of the project. Please check it out in [here](https://github.com/bounswe/bounswe2024group12/wiki/Milestone-Report-1).

**Comment by ArdaYalcindag** [comment]
Finished Executive Summary part of [Milestone 1 Report](https://github.com/bounswe/bounswe2024group12/wiki/Milestone-Report-1). Please check and inform me if you see anything to add or remove.
