### ISSUE TITLE
Write Table of Work Done by Each Team Member part of Milestone 1

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#80]
## Description

Create the "Table of Work Done by Each Team Member" for Milestone 1. This table should outline the tasks completed by each team member during this phase of the project.

***

## Acceptance Criteria
- [ ] The "Table of Work Done by Each Team Member" accurately reflects the tasks completed by each team member during Milestone 1.
- [ ] Any feedback or suggested revisions regarding the table are addressed and incorporated as needed.
<br>

***

### Reviewer:
This issue will be reviewed by: @abayir41 @ahmetfirat23 @yusufaygun

**Comment by ahmetfirat23** [comment]
We decided everyone should open this task for themselves individually.
