### ISSUE TITLE
Write Evaluation of Tools and Processes part of Milestone 1

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#81]
## Description

Compose the "Evaluation of Tools and Processes" section for Milestone 1 of the project documentation. This section should provide an assessment of the tools and processes used to manage the team project.

***

## Acceptance Criteria
- [x] The "Evaluation of Tools and Processes" section provides a comprehensive assessment of the tools and processes utilized to manage the team project.
- [x] Feedback from the reviewer has been considered and incorporated where appropriate to enhance the quality and clarity of the evaluation.
<br>

***

### Reviewer:
This issue will be reviewed by: @ahmetfirat23 @ArdaYalcindag

**Comment by isilsukarakuzuu** [comment]
I wrote parts other than 4.3 and 4.7. I will update them today. You can review the other parts. @ahmetfirat23 @ArdaYalcindag

**Comment by ahmetfirat23** [comment]
4.1.5. might need a little bit revise and more explanation. Also 4.1.3. should be delegated to task #79 . Other than these points LGTM. Feel free to close after evaluating these points.

**Comment by isilsukarakuzuu** [comment]
Spoke with @sonerkuyar and addressed 4.1.3. Also provided explanations for 4.1.5. Closing this issue now.
