### ISSUE TITLE
Update Mehmet Batuhan Cok's personal efforts on their personal page and in Milestone 1 report

### ISSUE THREAD

**Issue by isilsukarakuzuu** [bounswe/bounswe2024group12#87]
## Description

Update and correct any deficiencies in the weekly effort tables on your personal page. Additionally, document your efforts throughout Milestone 1 in the 'Table of Work Done by Each Team Member' section of the Milestone 1 report.

***

## Acceptance Criteria
- [x] The weekly effort table on the team member's personal page is updated and corrected to accurately reflect their contributions.
- [x] The team member's efforts throughout Milestone 1 are clearly documented in the 'Table of Work Done by Each Team Member' section of the Milestone 1 report.
<br>

***

### Reviewer:
This issue will be reviewed by: @isilsukarakuzuu

**Comment by mbatuhancok** [comment]
Done
