### ISSUE TITLE
Write an intro for our wiki homepage?

### ISSUE THREAD

**Issue by ounuvar** [bounswe/bounswe2024group12#9]
We had a bullet item to write an "intro" for our wiki homepage in our first meeting but there doesn't seem to be anything to write at this point or I don't remember what we meant by that. Please anyone clarify or mention what could be written for now.  @isilsukarakuzuu was the assignee in the meeting notes.

**Comment by isilsukarakuzuu** [comment]
It was aimed for improving the wiki's home page. I implemented it using the available information we have about the wiki. Done.
