### ISSUE TITLE
System and Software Design

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#95]
This phase focuses on outlining the system architecture and software specifications. It involves creating detailed designs and models that specify the system's components, their interactions, and how they will work together to meet the project requirements.

**Comment by ahmetfirat23** [comment]
End date of this milestone was extended to April 17th due to holiday break.

**Comment by ahmetfirat23** [comment]
Yet another extension was required for the due date of this milestone. It is extended 4 more days.

**Comment by ahmetfirat23** [comment]
@sonerkuyar Can you update this milestone's text in a similar format as previous ones for the sake of continuity?
