### ISSUE TITLE
Implementation

### ISSUE THREAD

**Issue by sonerkuyar** [bounswe/bounswe2024group12#96]
# Implementation

## Overview
During implementation, the system and software design plans are put into action. This involves coding, integrating various components, and developing the necessary functionalities. The goal is to transform the design documents into a working system.

### Frontend
- [x] #118 
- [x] #121 
- [x] #122
- [x] #131 
- [x] #132 
- [x] #135 
- [x] #136 
- [x] #152  
- [ ] Prepare documentation

### Backend
- [x] #126
- [x] #134
- [x] #133
- [x] #135
- [x] #150 
- [ ] #167 
- [x] #168 
- [x] #176 
- [x] #177 
- [x] #180 
- [x] #181 
- [ ] Prepare documentation (README.md)

### Mobile
- [x] #115 
- [ ] #129
- [x] #137
- [ ] Implement Login/Signup screen functionalities for mobile
- [x] #150
- [ ] #139 
- [x] #138 
- [ ] Implement Game screen functionalities for mobile
- [ ] Implement Main screen functionalities for mobile
...
- Prepare documentation

### Testing
- [ ] Manually test frontend components as they are completed
- [x] Manually test backend components as they are completed
- [ ] ?

### Deployment
- [x] Build, deploy and release frontend app
- [x] Build and release mobile app
- [x] Build, deploy and release backend app

## Deliverables
- [x] A properly functioning deployed MVP
- [x] A prerelease of the app
- [ ] Documentation for all parts
- [ ] Milestone report

**Comment by isilsukarakuzuu** [comment]
Let's talk about this in upcoming meeting on Wednesday @ArdaYalcindag @mbatuhancok

**Comment by ahmetfirat23** [comment]
I think adding these tasks to milestone was enough and we should give up using this technique. It is cumbersome for me to plan stuff out while we can just add milestone to issues.

**Comment by ahmetfirat23** [comment]
Since we submitted final milestone we won't be continuing implementation.
